// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owgvuifyicjosxuocjrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93Z3Z1aWZ5aWNqb3N4dW9janJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzMDMzMjksImV4cCI6MjA3Njg3OTMyOX0.9jfKOIC9ttI6FrJ0It0zFAQxrJHmAlgKdPk3R0R-gWI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});